version: "0.1"
user: vishnukdas
key: W1optvfbEMDg7YzC5PLFaEtLoX9PpPke4J2HwVhPCmUhazmBbe
testSuites: []
pre: [mkdir m2_cache_dir, mvn -Dmaven.repo.local=$CACHE_DIR -Dmaven.test.skip=true
    clean install]
env:
  CACHE_DIR: m2_cache_dir
jobLabel:
- api sample
runson: win
autosplit: true
concurrency: 1
testDiscovery:
  autosubset: true
  command: grep 'class name' src/test/java/testing.xml | awk '{print$2}' | sed 's/name=//g'
    | sed 's/\x3e//g'
  mode: dynamic
  type: raw
testRunnerCommand: mvn `-Dmaven.repo.local=$CACHE_DIR `-Dtest=$test `-Dbrowser=chrome
  `-Dversion=latest `-Dplatform="$HYPEREXECUTE_PLATFORM"
cacheDirectories:
- $CACHE_DIR
cacheKey: '{{ checksum "pom.xml" }}'
maxRetries: 5
jobID: 674513ac-cd2c-419c-891b-2180b8f7b31c
mergeArtifacts: true
codeDirectory: API_Sample
