version: "0.1"
user: vishnurv2
key: 2dEK8rin7XC3cChRqccFoMlcC9FwPNloQdqV9c4y7vFUAnAB18
testSuites: []
pre: [mkdir m2_cache_dir, mvn -Dmaven.repo.local=$CACHE_DIR -Dmaven.test.skip=true
    clean install]
env:
  CACHE_DIR: m2_cache_dir
jobLabel:
- api sample
runson: win
autosplit: true
concurrency: 1
testDiscovery:
  autosubset: true
  command: grep 'class name' src/test/java/testing.xml | awk '{print$2}' | sed 's/name=//g'
    | sed 's/\x3e//g'
  mode: dynamic
  type: raw
testRunnerCommand: mvn `-Dmaven.repo.local=$CACHE_DIR `-Dtest=$test `-Dbrowser=chrome
  `-Dversion=latest `-Dplatform="$HYPEREXECUTE_PLATFORM"
cacheDirectories:
- $CACHE_DIR
cacheKey: '{{ checksum "pom.xml" }}'
maxRetries: 5
jobID: 2e93e27a-25da-4b56-9e6b-539379e1dd8f
mergeArtifacts: true
codeDirectory: API_Sample
