version: "0.1"
user: vishnurv2
key: 2dEK8rin7XC3cChRqccFoMlcC9FwPNloQdqV9c4y7vFUAnAB18
testSuites: []
pre: [mkdir m2_cache_dir, mvn -Dmaven.repo.local=$CACHE_DIR -Dmaven.test.skip=true
    clean install, mvn -Dtest=apitestingsample -Dbrowser=chrome -Dversion=latest -Dplatform=win10
    -DsuiteXmlFile=testing.xml, curl -v ipinfo.io]
post: [mvn -Dtest=postapi -DsuiteXmlFile=testing.xml]
env:
  CACHE_DIR: m2_cache_dir
runson: win
autosplit: true
concurrency: 1
testDiscovery:
  autosubset: true
  command: grep 'class name' src/test/java/testing.xml | awk '{print$2}' | sed 's/name=//g'
    | sed 's/\x3e//g'
  mode: dynamic
  type: raw
testRunnerCommand: mvn `-Dtest=webtest `-Dbrowser=chrome `-Dversion=latest `-Dplatform=win10
  `-DsuiteXmlFile=web.xml
cacheDirectories:
- $CACHE_DIR
cacheKey: '{{ checksum "pom.xml" }}'
maxRetries: 5
jobID: 1631c49e-15a4-4483-a407-abf5d0563073
mergeArtifacts: true
uploadArtefacts:
- name: Report
  path:
  - target/surefire-reports/**
codeDirectory: API_Sample
framework:
  name: ""
  flags: []
  discoveryFlags: []
  discoveryType: ""
  runnerFlags: []
  workingDirectory: ""
  isTestNGXMLSuite: false
  defaultReports: true
cypress: false
betaFeature:
  setPartiallyCompletedAsCompleted: false
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
